version: "3"

services:
  # MYSQL DB FOR TRANSACTIONS
  txdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --init-file /usr/local/bin/create-tables.sql
    volumes:
      - ./txdb/scripts/create-tables.sql:/usr/local/bin/create-tables.sql
      - ../data/btc/mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: transactions
      MYSQL_USER: ttest
      MYSQL_PASSWORD: ttest

  txins:
    build: ./txins

    environment:
      MYSQL_HOST: txdb
      MYSQL_DBNAME: transactions
      MYSQL_USER: root
      MYSQL_PASSWORD: test

  # BITCOIND FULL NODE
  bitcoind:
    build:
      ./from-repo

    volumes:
      - ../data/btc/blks:/block-data
      - ../data/btc/config:/config

    ports:
     - 28332:28332
     - 8333:8333

    logging:
      options:
        max-file: "5"
        max-size: "500k"

    #NB: this command does chown as a hack to write on the
    #    mapped volumes, would be better to use docker volumes
    #    but how to map a local dir to a docker volume?
    command:
      - "/bin/bash"
      - -c
      - |
          chown root:root /block-data && \
          chown root:root /config && \
          bitcoind \
            -datadir=/block-data \
            -conf=/config/bitcoin.conf \
            -dbcache=200 \
            -txindex=1 \
            -reindex


  # UNCONFIRMED TRANSACTION LOGGER
  txlog:
    build:
      ./txlog

    volumes:
      - ../data/btc/unc:/txs

    environment:
      RAWTX_SOURCE_ADDR: tcp://bitcoind:28332
      OUTPUT_FILE: "/txs/unctxs"
      RAWTX_COUNT_PER_FILE: 1000000
      RAWTX_COMPRESSED_LOGS: 1

    logging:
      options:
        max-file: "5"
        max-size: "500k"

    command:
      - "/bin/bash"
      - -c
      - |
          chown root:root /txs && \
          python3 -u /usr/local/bin/zmq_c.py
