version: "3"

services:
  test-rpc-py:
    build: ./test-rpc-py
    networks: [btc-logger-network]
    command:
      - "/bin/bash"
      - "-c"
      - "hostname -i && python -u /usr/local/bin/getchaininfo.py"
    environment:
      RPC_HOST: bitcoind
      RPC_PORT: $BITCOIND_RPC_PORT
      RPC_USER: $BITCOIND_RPC_USER
      RPC_PASS: $BITCOIND_RPC_PASS

  test-rpc-curl:
    image: pstauffer/curl
    networks: [btc-logger-network]
    command:
     - "/bin/sh"
     - "-c"
     - |
         hostname -i && \
         curl \
           -v \
           -u $BITCOIND_RPC_USER:$BITCOIND_RPC_PASS \
           -d '{"jsonrpc": "2.0", "id":"curltest", "method": "getblockchaininfo", "params": [] }' \
           -H 'content-type: text/plain;' \
           http://bitcoind:$BITCOIND_RPC_PORT/

  # BITCOIND FULL NODE
  bitcoind:
    build: ./from-repo
    volumes: [../data/btc/blks:/block-data]
    networks: [btc-logger-network]
    ports:
     - 28332:28332
     - $BITCOIND_RPC_PORT:$BITCOIND_RPC_PORT

    logging:
      options:
        max-file: "5"
        max-size: "500k"

    #NB: this command does chown as a hack to write on the
    #    mapped volumes, would be better to use docker volumes
    #    but how to map a local dir to a docker volume?
    command:
      - "/bin/bash"
      - -c
      - |
          chown root:root /block-data && \
          bitcoind \
            -datadir=/block-data \
            -dbcache=200 \
            -txindex=1 \
            -reindex \
            -zmqpubrawtx=tcp://0.0.0.0:$BITCOIND_ZMQ_PORT \
            -zmqpubhashblock=tcp://0.0.0.0:$BITCOIND_ZMQ_PORT \
            -server \
            -rpcuser=$BITCOIND_RPC_USER \
            -rpcpassword=$BITCOIND_RPC_PASS \
            -rpcallowip=$BTC_NETMASK \
            -rpcbind=0.0.0.0:$BITCOIND_RPC_PORT \
            -rpcport=$BITCOIND_RPC_PORT

#            -debug=rpc \
#            -debug=net \
#            -debug=http

  # UNCONFIRMED TRANSACTION LOGGER
  txlog:
    build:
      ./txlog

    volumes:
      - ../data/btc/unc:/txs

    environment:
      RAWTX_SOURCE_ADDR: tcp://bitcoind:$BITCOIND_ZMQ_PORT
      OUTPUT_FILE: "/txs/unctxs"
      RAWTX_COUNT_PER_FILE: 1000000
      RAWTX_COMPRESSED_LOGS: 1
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USER: root
      MONGODB_PASS: test
      BITCOIND_HOST: bitcoind
      BITCOIND_PORT: $BITCOIND_RPC_PORT
      BITCOIND_RPC_USER: $BITCOIND_RPC_USER
      BITCOIND_RPC_PASSWORD: $BITCOIND_RPC_PASS

    logging:
      options:
        max-file: "5"
        max-size: "500k"

    command:
      - "/bin/bash"
      - -c
      - |
          chown root:root /txs && \
          python3 -u /usr/local/bin/zmq_c.py

  # MONGODB FOR TRANSACTIONS
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

networks:
  btc-logger-network:
    ipam:
      driver: default
      config:
        - subnet: $BTC_LOGGER_NETMASK
