version: "3"

networks:
  # network to contain the services
  # NB: the mask is important for bitcoind permissions
  default:
    external:
      name: btc-logger-network

services:
  # RPC TESTS
  # test remote producecalls to bitcoind from a python script
  test-rpc-py:
    build:
      context: ./test-rpc-py
      args:
        BASE_IMAGE: $PYTHON_ZMQ_IMAGE

    networks: [btc-logger-network]
    command:
      - "/bin/sh"
      - "-c"
      - "hostname -i && python -u /usr/local/bin/getchaininfo.py"
    environment:
      RPC_HOST: bitcoind
      RPC_PORT: $BITCOIND_RPC_PORT
      RPC_USER: $BITCOIND_RPC_USER
      RPC_PASS: $BITCOIND_RPC_PASS
    logging:
      options:
        max-file: "4"
        max-size: "100k"

  # test rpc to bitcoind from curl
  test-rpc-curl:
    build: ./test-rpc-curl
    networks: [btc-logger-network]
    command:
     - "/bin/sh"
     - "-c"
     - |
         hostname -i && \
         curl \
           -v \
           -u $BITCOIND_RPC_USER:$BITCOIND_RPC_PASS \
           -d '{"jsonrpc": "2.0", "id":"curltest", "method": "getblockchaininfo", "params": [] }' \
           -H 'content-type: text/plain;' \
           http://bitcoind:$BITCOIND_RPC_PORT/
    logging:
      options:
        max-file: "4"
        max-size: "100k"
