version: "3"

services:
  mongo-storage-static:
    image: mongo
    volumes:
      - $DATA_DIR/data/static-store:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    expose:
      - 27017

  read-data:
    build: ./graph-vis
    volumes:
      - $DATA_DIR/images:/output-images
    environment:
      MONGODB_HOST: mongo-storage-static
      MONGODB_PORT: 27017
      MONGODB_USER: $MONGODB_USER
      MONGODB_PASS: $MONGODB_PASSWORD
      MONGODB_AUTHDB: admin
      MONGODB_DATABASE: $MONGODB_DATABASE
      MONGODB_COLLECTION: $MONGODB_COLLECTION
    command:
      - "/bin/bash"
      - "-c"
      - "python3 /usr/local/bin/make-graph.py"
    depends_on:
      - mongo-storage-static
