version: "3"

services:
  mongo-storage-static:
    image: mongo
    volumes:
      - $DATA_DIR/data/static-store:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    expose:
      - 27017

  mongo-restore-backup:
    image: mongo
    volumes:
      - $DATA_DIR/backup/:/backup 
    command:
      - "/bin/bash"
      - "-c"
      - |
          sleep 10 && \
          gzip \
           -c \
           -d \
           /backup/export.mongodbo.gz | \
          mongorestore \
           --host mongo-storage-static \
           --port 27017 \
           --username $MONGODB_USER \
           --password $MONGODB_PASSWORD \
           --archive
    depends_on:
      - mongo-storage-static

  # this will run over whatever data has been restored,
  # if the restore is long running, just up this service
  # later manually
  graph-vis:
    build: ./graph-vis
    volumes:
      - $DATA_DIR/images:/output-images
    environment:
      MONGODB_HOST: mongo-storage-static
      MONGODB_PORT: 27017
      MONGODB_USER: $MONGODB_USER
      MONGODB_PASS: $MONGODB_PASSWORD
      MONGODB_AUTHDB: admin
      MONGODB_DATABASE: $MONGODB_DATABASE
      MONGODB_COLLECTION: $MONGODB_COLLECTION
    command:
      - "/bin/bash"
      - "-c"
      - "sleep 20 && python3 /usr/local/bin/make-graph.py"
    depends_on:
      - mongo-storage-static
      - mongo-restore-backup
