version: "3"

services:
  mongo-storage-static:
    image: mongo
    volumes:
      - $DATA_DIR/data/static-store:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    expose:
      - 27017

  mongo-restore-backup:
    image: mongo
    volumes:
      - $DATA_DIR/backup/:/backup 
    command:
      - "/bin/bash"
      - "-c"
      - |
          sleep 10 && \
          gzip \
           -c \
           -d \
           /backup/tx-db-201510-20p.gz | \
          mongorestore \
           --host mongo-storage-static \
           --port 27017 \
           --username $MONGODB_USER \
           --password $MONGODB_PASSWORD \
           --archive
    depends_on:
      - mongo-storage-static

#           --authenticationDatabase admin \

