version: "3"

networks:
  # network to contain the services
  # NB: the mask is important for bitcoind permissions
  default:
    external:
      name: btc-logger-network

services:
  confirm-transactions:
    build:
      context: ./transaction-confirmer
      args:
        BASE_IMAGE: $PYTHON_ZMQ_IMAGE
    networks: [btc-logger-network]
    volumes:
      - $DATA_DIR/txs/:/data
    environment:
      RPC_HOST: bitcoind
      RPC_PORT: $BITCOIND_RPC_PORT
      RPC_USER: $BITCOIND_RPC_USER
      RPC_PASS: $BITCOIND_RPC_PASS
      TX_READ_COUNT: 400
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION_NAME: $AWS_REGION_NAME
      AWS_BUCKET_NAME: $AWS_BUCKET_NAME
    command: >
      /bin/sh -c "aws s3 cp s3://$AWS_BUCKET_NAME/$AWS_AGG_PREFIX/$TRANSACTION_FILE $LOCAL_DATA_DIR/$TRANSACTION_FILE &&
                  python /usr/local/bin/getrawtransaction.py $LOCAL_DATA_DIR/$TRANSACTION_FILE $LOCAL_DATA_DIR/$TRANSACTION_LABEL_FILE &&
                  aws s3 cp $LOCAL_DATA_DIR/$TRANSACTION_LABEL_FILE s3://$AWS_BUCKET_NAME/$AWS_AGG_PREFIX/$TRANSACTION_LABEL_FILE"
